name: CI only

on:
  push:
    branches-ignore:
      - main
  pull_request:

env:
  SECRETS_MANAGER_ACCESS_TOKEN: ${{ secrets.SECRETS_MANAGER_ACCESS_TOKEN }}

jobs:
  ci-only:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download config server
        uses: robinraju/release-downloader@v1.8
        with:
          repository: "simpleg-eu/cp-config"
          latest: true
          fileName: "app.zip"
          out-file-path: "cp-config"
          extract: true
      - name: Run config server
        run: |
          mkdir bin
          cd bin
          curl -LO https://github.com/bitwarden/sdk/releases/download/bws-v0.3.0/bws-x86_64-unknown-linux-gnu-0.3.0.zip
          unzip bws-x86_64-unknown-linux-gnu-0.3.0.zip
          chmod +x bws
          export PATH=$PATH:$PWD
          cd ../
          cd cp-config
          chmod +x cp-config
          ./cp-config config.yaml &
          cd ../
      - name: Run tests
        run: |
          cargo test --all-features